// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
  "/transactions": {
    params: {};
  };
  "/budget": {
    params: {};
  };
  "/reports": {
    params: {};
  };
  "/walkthrough": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/register" | "/auth/logout" | "/transactions" | "/budget" | "/reports" | "/walkthrough" | "/*";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.register.tsx": {
    id: "routes/auth.register";
    page: "/auth/register";
  };
  "routes/auth.logout.tsx": {
    id: "routes/auth.logout";
    page: "/auth/logout";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/" | "/transactions" | "/budget" | "/reports" | "/walkthrough";
  };
  "routes/_app.dashboard.tsx": {
    id: "routes/_app.dashboard";
    page: "/";
  };
  "routes/_app.transactions.tsx": {
    id: "routes/_app.transactions";
    page: "/transactions";
  };
  "routes/_app.budget.tsx": {
    id: "routes/_app.budget";
    page: "/budget";
  };
  "routes/_app.reports.tsx": {
    id: "routes/_app.reports";
    page: "/reports";
  };
  "routes/walkthrough.tsx": {
    id: "routes/walkthrough";
    page: "/walkthrough";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.register": typeof import("./app/routes/auth.register.tsx");
  "routes/auth.logout": typeof import("./app/routes/auth.logout.tsx");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/_app.dashboard": typeof import("./app/routes/_app.dashboard.tsx");
  "routes/_app.transactions": typeof import("./app/routes/_app.transactions.tsx");
  "routes/_app.budget": typeof import("./app/routes/_app.budget.tsx");
  "routes/_app.reports": typeof import("./app/routes/_app.reports.tsx");
  "routes/walkthrough": typeof import("./app/routes/walkthrough.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};