// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
  "/auth/forgot-password": {
    params: {};
  };
  "/transactions": {
    params: {};
  };
  "/budget": {
    params: {};
  };
  "/reports": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/profile/edit": {
    params: {};
  };
  "/profile/security": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/walkthrough": {
    params: {};
  };
  "/api/*": {
    params: {
      "*": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/register" | "/auth/logout" | "/auth/forgot-password" | "/transactions" | "/budget" | "/reports" | "/profile" | "/profile/edit" | "/profile/security" | "/settings" | "/walkthrough" | "/api/*" | "/*";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.register.tsx": {
    id: "routes/auth.register";
    page: "/auth/register";
  };
  "routes/auth.logout.tsx": {
    id: "routes/auth.logout";
    page: "/auth/logout";
  };
  "routes/auth.forgot-password.tsx": {
    id: "routes/auth.forgot-password";
    page: "/auth/forgot-password";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/" | "/transactions" | "/budget" | "/reports" | "/profile" | "/profile/edit" | "/profile/security" | "/settings";
  };
  "routes/_app.dashboard.tsx": {
    id: "routes/_app.dashboard";
    page: "/";
  };
  "routes/_app.transactions.tsx": {
    id: "routes/_app.transactions";
    page: "/transactions";
  };
  "routes/_app.budget.tsx": {
    id: "routes/_app.budget";
    page: "/budget";
  };
  "routes/_app.reports.tsx": {
    id: "routes/_app.reports";
    page: "/reports";
  };
  "routes/_app.profile.tsx": {
    id: "routes/_app.profile";
    page: "/profile";
  };
  "routes/_app.profile_.edit.tsx": {
    id: "routes/_app.profile_.edit";
    page: "/profile/edit";
  };
  "routes/_app.profile_.security.tsx": {
    id: "routes/_app.profile_.security";
    page: "/profile/security";
  };
  "routes/_app.settings.tsx": {
    id: "routes/_app.settings";
    page: "/settings";
  };
  "routes/walkthrough.tsx": {
    id: "routes/walkthrough";
    page: "/walkthrough";
  };
  "routes/api.$.tsx": {
    id: "routes/api.$";
    page: "/api/*";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.register": typeof import("./app/routes/auth.register.tsx");
  "routes/auth.logout": typeof import("./app/routes/auth.logout.tsx");
  "routes/auth.forgot-password": typeof import("./app/routes/auth.forgot-password.tsx");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/_app.dashboard": typeof import("./app/routes/_app.dashboard.tsx");
  "routes/_app.transactions": typeof import("./app/routes/_app.transactions.tsx");
  "routes/_app.budget": typeof import("./app/routes/_app.budget.tsx");
  "routes/_app.reports": typeof import("./app/routes/_app.reports.tsx");
  "routes/_app.profile": typeof import("./app/routes/_app.profile.tsx");
  "routes/_app.profile_.edit": typeof import("./app/routes/_app.profile_.edit.tsx");
  "routes/_app.profile_.security": typeof import("./app/routes/_app.profile_.security.tsx");
  "routes/_app.settings": typeof import("./app/routes/_app.settings.tsx");
  "routes/walkthrough": typeof import("./app/routes/walkthrough.tsx");
  "routes/api.$": typeof import("./app/routes/api.$.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};